server:
  port: 8081

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwkSetUri: http://localhost:8080/realms/oauth2/protocol/openid-connect/certs
#          jwsAlgorithms: RS256
#          publicKeyLocation: classpath:certs/publicKey.txt
